### ISSUE TITLE
Project errors with node@lts

### ISSUE THREAD

**Issue by anthonycastelli** [netlify/netlify-statuskit#54]
When trying to create a new incident via `npm run new-incident` it fails trying load everything. I've run `npm install` and worked out as many issues as I could but have had no luck. I just deployed this to netlify and it all worked well. I wanted to create an incident just to test things out, but no luck. 

Here is my full output log
```
npm run new-incident                                    ✘ 1 master ✱

> netlify-statusKit@1.0.0 new-incident /Users/anthony/Documents/Projects/Canteen/Server/Status
> gulp new-incident

[11:42:23] Failed to load external module @babel/register
[11:42:23] Requiring external module babel-register
assert.js:351
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/Users/anthony/Documents/Projects/Canteen/Server/Status/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/Users/anthony/Documents/Projects/Canteen/Server/Status/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/Users/anthony/Documents/Projects/Canteen/Server/Status/gulpfile.babel.js:26:6)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at loader (/Users/anthony/Documents/Projects/Canteen/Server/Status/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/anthony/Documents/Projects/Canteen/Server/Status/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at execute (/Users/anthony/Documents/Projects/Canteen/Server/Status/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:36:18)
    at Liftoff.handleArguments (/Users/anthony/Documents/Projects/Canteen/Server/Status/node_modules/gulp/node_modules/gulp-cli/index.js:175:63)
    at Liftoff.execute (/Users/anthony/Documents/Projects/Canteen/Server/Status/node_modules/liftoff/index.js:203:12)
    at module.exports (/Users/anthony/Documents/Projects/Canteen/Server/Status/node_modules/flagged-respawn/index.js:51:3)
    at Liftoff.<anonymous> (/Users/anthony/Documents/Projects/Canteen/Server/Status/node_modules/liftoff/index.js:195:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! netlify-statusKit@1.0.0 new-incident: `gulp new-incident`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the netlify-statusKit@1.0.0 new-incident script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/anthony/.npm/_logs/2018-11-08T19_42_25_422Z-debug.log
```

I'm not a Node developer so this is a bit over my head. My version info is stated below too.

macOS 10.14
Node v11.1.0
npm v6.4.1

**Comment by steveoh** [comment]
I want to say this is an issue with the version of node and one of the packages. If you have nvm try going down to LTS and try it there to see if it works.

**Comment by anthonycastelli** [comment]
I will take a look tonight and try again.

**Comment by Suleman-Elahi** [comment]
Today Checked and on my Windows 10 PC.. it is running fine...

**Comment by anthonycastelli** [comment]
I managed to find a way around it by downgrading some components and specifying exact versions.

**Comment by steveoh** [comment]
Share that so the npm packages can be pinned for others

**Comment by steveoh** [comment]
I updated status kit in my branch to work on node lts. I'm hesitant to take the time to create a PR if netlify is not going to take the time to review and accept it.
